# Generated by Django 2.2.6 on 2019-11-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
