# Generated by Django 2.2.6 on 2019-11-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_delete_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book')),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='borrower',
            field=models.ManyToManyField(through='p_library.Rent', to='p_library.Friend'),
        ),
    ]
