# Generated by Django 2.2.6 on 2019-11-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20191118_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='num',
            field=models.SmallIntegerField(default=1),
        ),
    ]
