# Generated by Django 2.2.6 on 2019-11-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20191118_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrower',
        ),
        migrations.AddField(
            model_name='friend',
            name='book',
            field=models.ManyToManyField(through='p_library.Rent', to='p_library.Book'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_name',
            field=models.TextField(),
        ),
    ]
