# Generated by Django 2.2.6 on 2019-11-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20191118_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
        ),
    ]
