# Generated by Django 2.2.6 on 2019-11-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_auto_20191118_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
