# Generated by Django 2.2.6 on 2019-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0017_remove_book_can_be_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='can_be_borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
