# Generated by Django 2.2.6 on 2019-11-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0018_book_can_be_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='can_be_borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
