# Generated by Django 2.2.6 on 2019-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0019_auto_20191121_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='can_be_borrowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.IntegerField(default=1),
        ),
    ]
